### PR TITLE
Addition of the SkyTrain, Edmonton LRT and C-Train.

### PR DESCRIPTION
**Pull request by davidbellerive**
Addition of the SkyTrain, Edmonton LRT and Calgary C-Train using OSM and visual data. 

Does not include the future maintenance / storage facility at North Road as I could not confirm the exact track layout for Vancouver.

Calgary should be rather final, does not include planned or proposed lines.

Edmonton Capital and Metro Line are alignments and not tracks, also lacks the maintenance facility (to be added later). Valley Line Southeast and West are tracks, though I believe some switches are missing.

(Branch rename downstream)

### CODE REVIEW

**Review by dellisd — CHANGES_REQUESTED** [review]
I think we should just use a single `skytrain` filter key for the entire skytrain network since it doesn't make as much sense to break it down per-line as it did with VIA. The Broadway extension of the Millenium line should be split off into its own file however and have a separate filter key, like we do for all other in-progress extensions.

The really tricky thing about using the line offsets is that every `LineString` needs to be oriented in the same direction across the entire dataset. If they're not, then the lines will be offset in whatever random direction the line is pointing in.

This is most evident at switches where you can see that the diverging tracks are being offset in the opposite direction compared to the mainline tracks, meaning they end up sticking out.

image

The way I've fixed this in the past with QGIS is to modify the symbology for the line layer to add an arrow symbol which points in the direction of the string (as shown below with GO data). Then I select individual line entries and using `Ctrl+K` to locate the "Reverse line direction" tool to flip the direction of individual segments until the entire thing is pointing in a uniform direction.

image

It's tedious unfortunately, but the results are worth it!

**Comment by davidbellerive** [comment]
Totally agree on the single filterkey. Will be arranging the lines and update the pull.

**Comment by dellisd** [comment]
I think we can drop the filter key for the vancouver lines, but I also see that the Broadway extension isn't there anymore. Is that intentional?

Otherwise I think this okay to merge.

**Comment by davidbellerive** [comment]
For the broadway extension: intentional. I couldnt exactly confirm the station layout versus the tracks. i could add back the broadway extension if okay with lack of detail.Filter key might have been added by mistake on my end, as you see fit!On Dec 23, 2022, at 18:57, Derek Ellis ***@***.***> wrote:﻿
I think we can drop the filter key for the vancouver lines, but I also see that the Broadway extension isn't there anymore. Is that intentional?
Otherwise I think this okay to merge.

**Comment by dellisd** [comment]
The Expo and Millennium lines will need to be offset slightly so that they don't overlap here. They can be offset by `0.5` in opposite directions to get them to line up nicely.
image

**Review by dellisd — APPROVED** [review]

**Pull request merged**
